name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
   set-up:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
   check:
    runs-on: ubuntu-latest
    needs: set-up
    steps:
      - name: Practice
        run: |
            echo "Found Found"
   build:
    runs-on: ubuntu-latest
    needs: set-up
    

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          repo_name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          docker build -t service-a:latest ./multi-docker-project/service-a
          docker build -t service-b:latest ./multi-docker-project/service-b
          docker tag service-a:latest ghcr.io/$owner/$repo_name/service-a:latest
          docker tag service-b:latest ghcr.io/$owner/$repo_name/service-b:latest
          docker push ghcr.io/$owner/$repo_name/service-a:latest
          docker push ghcr.io/$owner/$repo_name/service-b:latest

          
          
