name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build and Push Docker Images (tagged :latest)
        run: |
          echo "🔍 Finding Dockerfiles..."

          find . -type f -name 'Dockerfile' | while read dockerfile; do
            context_dir=$(dirname "$dockerfile")
            image_name=$(echo "$context_dir" | sed 's|^\./||' | tr '/A-Z' '-a-z' | tr -c 'a-z0-9-_' '-')

            image="ghcr.io/${{ github.repository_owner }}/$image_name:latest"

            echo "🛠 Building $image from $dockerfile"
            docker build -f "$dockerfile" -t "$image" "$context_dir"

            echo "🚀 Pushing $image"
            docker push "$image"
          done
