name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: service-a
            context: ./multi-docker-project/service-a
          - name: service-b
            context: ./multi-docker-project/service-b
          - name: sub-profile-b1
            context: multi-docker-project/service-b/sub-profile-b1
          - name: service-c
            context: ./multi-docker-project/service-c

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build and Push Docker Images
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          repo_name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${{ matrix.name }}:latest ${{ matrix.context }}
          docker tag ${{ matrix.name }}:latest ghcr.io/$owner/$repo_name/${{ matrix.name }}:latest
          docker push ghcr.io/$owner/$repo_name/${{ matrix.name }}:latest
          
