name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
   build:
    runs-on: ubuntu-latest
    

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build and Push Docker Images
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          repo_name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          docker build -t service-a:latest ./multi-docker-project/service-a
         
          docker tag service-a:latest ghcr.io/$owner/$repo_name/service-a:latest
         
          docker push ghcr.io/$owner/$repo_name/service-a:latest
       

          
          
